### ISSUE TITLE
Should a budget’s categories be able to be changed after they are created?

### ISSUE THREAD

**Issue by hmartyscu** [CSC207-UofT/course-project-group-054#17]
Currently, once the categories in a Budget are set, they cannot be modified. Should they be able to be modified?

https://github.com/CSC207-UofT/course-project-group-054/blob/062af5260301f8f44161f65bd66da209560f7221/src/main/java/entities/Budget.java#L30

**Comment by rohantinna** [comment]
Yeah I think that could be a useful feature if a person accidentally selects the wrong category

**Comment by hmartyscu** [comment]
I eliminated the categories, as described in the design document.
