### ISSUE TITLE
Style frontend

### ISSUE THREAD

**Issue by AccountForCSC** [CSC207-UofT/course-project-group-054#29]
I am working on styling the frontend.

**Comment by AccountForCSC** [comment]
I made the Sign Up page look like this:

<img width="648" alt="sign-up-screenshot-3" src="https://user-images.githubusercontent.com/92616103/142742787-1408212d-4bc0-4275-8523-5a26e0b215fc.png">

**Comment by AccountForCSC** [comment]
Added more space above the Sign Up button:

<img width="656" alt="sign-up-screenshot-4" src="https://user-images.githubusercontent.com/92616103/142743028-4c92f460-170c-402d-beab-9b77e57a1e0d.png">

**Comment by AccountForCSC** [comment]
https://user-images.githubusercontent.com/92616103/142746582-5bd535ee-9b9b-434d-999e-60412c074130.mov

**Comment by AccountForCSC** [comment]
https://user-images.githubusercontent.com/92616103/142747790-d790e9a4-f40f-45fa-9238-a4a6f9f5e19f.mov

**Comment by AccountForCSC** [comment]
https://user-images.githubusercontent.com/92616103/142778608-d9ca6134-1885-4aa6-9bd5-d731eff1898a.mov

**Comment by AccountForCSC** [comment]
The dashboard adapts to the user's screen by stacking the two boxes vertically and making the buttons bigger, when the user is viewing a smaller screen, such as a tablet screen.

**Comment by hmartyscu** [comment]
If you add a section for displaying and managing a user's profile, I think the dashboard page will have the same functionality as the dashboard method in the command-line Controller.
