### ISSUE TITLE
Password in frontend

### ISSUE THREAD

**Issue by AccountForCSC** [CSC207-UofT/course-project-group-054#37]

**Comment by AccountForCSC** [comment]
https://user-images.githubusercontent.com/92616103/143329881-ba8ec903-38c5-425f-aaa6-1ed559a12d9d.mov

**Comment by AccountForCSC** [comment]
https://user-images.githubusercontent.com/92616103/143512936-63abd66d-b5db-4f6a-8691-ab86edb0ecb3.mov

**Comment by johnnyjly** [comment]
Looks good.
